import type { ToolMode } from "@/components/PdfToolkit";

export const SITE_URL = "https://private-pdf-toolkit.vercel.app";

export type ToolPage = {
  slug: string;
  mode: ToolMode;
  h1: string;
  metaTitle: string;
  description: string;
  keyword: string;
  benefit: string;
};

export const toolPages: ToolPage[] = [
  { slug: "merge-pdf-free", mode: "merge", h1: "Merge PDF Online Free", metaTitle: "Merge PDF Online Free - 100% Private (No File Upload)", description: "Combine PDF files free in your browser. No upload, account, watermark or server processing.", keyword: "merge PDF free", benefit: "combine reports, contracts and attachments in the order you choose" },
  { slug: "merge-pdf-online", mode: "merge", h1: "Private Online PDF Merger", metaTitle: "Merge PDF Online - Fast, Free & Private", description: "Merge PDFs online with local browser processing and instant download.", keyword: "merge PDF online", benefit: "create one organized document from multiple PDFs" },
  { slug: "combine-pdf-files", mode: "merge", h1: "Combine PDF Files Securely", metaTitle: "Combine PDF Files Online - No Upload Required", description: "Combine multiple PDF files without sending confidential documents to a cloud service.", keyword: "combine PDF files", benefit: "assemble polished document packets while keeping data on-device" },
  { slug: "merge-pdf-no-upload", mode: "merge", h1: "Merge PDF Without Uploading", metaTitle: "Merge PDF Without Upload - Private Browser Tool", description: "A no-upload PDF merger that processes every file locally on your device.", keyword: "merge PDF no upload", benefit: "merge sensitive documents without a server copy" },
  { slug: "merge-pdf-for-work", mode: "merge", h1: "Merge PDFs for Work", metaTitle: "Merge PDFs for Work - Fast Private Office Tool", description: "Combine business PDFs, invoices and reports quickly without an account.", keyword: "merge PDFs for work", benefit: "prepare client-ready packets during a busy workday" },
  { slug: "secure-pdf-merger", mode: "merge", h1: "Secure PDF Merger", metaTitle: "Secure PDF Merger - Client-Side & Free", description: "Merge documents with a security-first tool that never uploads your source files.", keyword: "secure PDF merger", benefit: "keep confidential source files under your control" },
  { slug: "merge-invoice-pdfs", mode: "merge", h1: "Merge Invoice PDFs", metaTitle: "Merge Invoice PDFs Free - No Upload or Signup", description: "Combine invoices into one clean PDF locally for finance, records or email.", keyword: "merge invoice PDFs", benefit: "bundle monthly invoices into one easy-to-share file" },
  { slug: "combine-scanned-documents", mode: "merge", h1: "Combine Scanned Documents", metaTitle: "Combine Scanned PDF Documents Privately", description: "Put scanned PDF pages and documents into the right order without uploading them.", keyword: "combine scanned documents", benefit: "turn separate scans into one correctly ordered PDF" },
  { slug: "split-pdf-online", mode: "split", h1: "Split PDF Online Privately", metaTitle: "Split PDF Online Free - Extract Pages Privately", description: "Split PDFs and extract selected pages with no file uploads or cloud storage.", keyword: "split PDF online", benefit: "save only the pages you need from a larger document" },
  { slug: "split-pdf-free", mode: "split", h1: "Free PDF Splitter", metaTitle: "Split PDF Free - No Signup, No Watermark", description: "Use a free local PDF splitter with flexible page ranges and clean downloads.", keyword: "split PDF free", benefit: "create a smaller focused PDF in seconds" },
  { slug: "extract-pdf-pages", mode: "split", h1: "Extract Pages from PDF", metaTitle: "Extract PDF Pages Online - Secure & Free", description: "Extract pages like 1-3, 5 from any PDF entirely inside your browser.", keyword: "extract PDF pages", benefit: "pull selected pages into a new standalone PDF" },
  { slug: "separate-pdf-pages", mode: "split", h1: "Separate PDF Pages", metaTitle: "Separate PDF Pages Online Without Uploading", description: "Separate the exact PDF pages you need without sending the file over the internet.", keyword: "separate PDF pages", benefit: "isolate forms, chapters or attachments from a PDF" },
  { slug: "split-pdf-no-upload", mode: "split", h1: "Split PDF Without Upload", metaTitle: "Split PDF Without Upload - Private Local Tool", description: "Split sensitive PDFs with zero server uploads. Your browser does the work locally.", keyword: "split PDF no upload", benefit: "extract confidential pages with minimal exposure" },
  { slug: "pdf-page-extractor", mode: "split", h1: "PDF Page Extractor", metaTitle: "PDF Page Extractor - Free Client-Side Tool", description: "A fast browser-based PDF page extractor for custom ranges and individual pages.", keyword: "PDF page extractor", benefit: "make a new PDF from any custom page selection" },
  { slug: "jpg-to-pdf-converter", mode: "image", h1: "JPG to PDF Converter", metaTitle: "JPG to PDF Converter Free - Private & Fast", description: "Convert one or many JPG images to a standard PDF with local processing.", keyword: "JPG to PDF converter", benefit: "turn photos and scans into a professional PDF" },
  { slug: "png-to-pdf-converter", mode: "image", h1: "PNG to PDF Converter", metaTitle: "PNG to PDF Converter - Free, Private, No Upload", description: "Convert PNG files into an A4 PDF without uploading images to a server.", keyword: "PNG to PDF converter", benefit: "package PNG graphics into a shareable document" },
  { slug: "image-to-pdf-free", mode: "image", h1: "Convert Images to PDF Free", metaTitle: "Image to PDF Free - JPG & PNG, No Upload", description: "Convert JPG and PNG images to PDF free with automatic page fitting.", keyword: "image to PDF free", benefit: "combine mixed images into one tidy PDF" },
  { slug: "photos-to-pdf", mode: "image", h1: "Convert Photos to PDF", metaTitle: "Photos to PDF Converter - Private Browser Tool", description: "Convert multiple photos to a single PDF in the order you choose.", keyword: "photos to PDF", benefit: "turn phone photos into an easy-to-file document" },
  { slug: "convert-jpg-to-pdf-no-upload", mode: "image", h1: "Convert JPG to PDF Without Upload", metaTitle: "Convert JPG to PDF Without Uploading", description: "Keep private images on your device while converting JPG files to PDF.", keyword: "JPG to PDF no upload", benefit: "convert sensitive scans without a cloud copy" },
  { slug: "multiple-images-to-pdf", mode: "image", h1: "Multiple Images to One PDF", metaTitle: "Combine Multiple Images into One PDF Free", description: "Arrange multiple JPG and PNG images and export one standard PDF locally.", keyword: "multiple images to PDF", benefit: "assemble many images into one ordered file" },
  { slug: "compress-pdf-no-upload", mode: "compress", h1: "Compress PDF Without Upload", metaTitle: "Compress PDF No Upload - 100% Private", description: "Repack and clean a PDF locally with no upload, account or server retention.", keyword: "compress PDF no upload", benefit: "optimize PDF structure while retaining local control" },
  { slug: "compress-pdf-online-free", mode: "compress", h1: "Compress PDF Online Free", metaTitle: "Compress PDF Online Free - Private Local Processing", description: "Optimize and repack PDF files in your browser for free.", keyword: "compress PDF online free", benefit: "produce a cleaner, efficiently packaged PDF" },
  { slug: "reduce-pdf-file-size", mode: "compress", h1: "Reduce PDF File Size", metaTitle: "Reduce PDF File Size Privately in Your Browser", description: "Repackage PDF objects and remove metadata without sending documents online.", keyword: "reduce PDF file size", benefit: "reduce structural overhead in compatible documents" },
  { slug: "optimize-pdf-for-email", mode: "compress", h1: "Optimize PDF for Email", metaTitle: "Optimize PDF for Email - Free Private Tool", description: "Clean and repack a PDF before attaching it to email, entirely on-device.", keyword: "optimize PDF for email", benefit: "prepare a cleaner PDF for workplace sharing" },
  { slug: "compress-pdf-for-email", mode: "compress", h1: "Compress PDF for Email", metaTitle: "Compress PDF for Email Without Uploading", description: "Try private PDF repacking before sending a large document by email.", keyword: "compress PDF for email", benefit: "make compatible documents easier to attach and send" },
  { slug: "clean-pdf-metadata", mode: "compress", h1: "Clean PDF Metadata", metaTitle: "Clean PDF Metadata Free - Private Browser Tool", description: "Remove common PDF document information and XMP metadata locally.", keyword: "clean PDF metadata", benefit: "strip common hidden author and document properties" },
  { slug: "remove-pdf-metadata", mode: "compress", h1: "Remove PDF Metadata", metaTitle: "Remove PDF Metadata Without Uploading", description: "Remove common metadata fields from PDFs without sharing the document with a server.", keyword: "remove PDF metadata", benefit: "create a cleaner copy before external sharing" },
  { slug: "private-pdf-tools", mode: "merge", h1: "Private PDF Tools", metaTitle: "Private PDF Tools - Files Never Leave Your Device", description: "A free privacy-first toolbox for merging, splitting, converting and cleaning PDFs.", keyword: "private PDF tools", benefit: "complete everyday PDF tasks without surrendering file privacy" },
  { slug: "offline-pdf-tools-browser", mode: "merge", h1: "Browser-Based Offline PDF Tools", metaTitle: "Offline PDF Tools in Your Browser - No Upload", description: "Load the app, then process supported PDF tasks locally without transferring files.", keyword: "offline PDF tools browser", benefit: "work with documents using local browser resources" },
  { slug: "pdf-tools-no-signup", mode: "merge", h1: "PDF Tools with No Signup", metaTitle: "Free PDF Tools - No Signup or Account", description: "Use essential PDF tools immediately with no registration, email or account.", keyword: "PDF tools no signup", benefit: "finish simple document work without creating an account" },
  { slug: "pdf-tools-no-watermark", mode: "image", h1: "PDF Tools with No Watermark", metaTitle: "PDF Tools Without Watermarks - Free & Private", description: "Create and process PDFs locally without adding promotional watermarks.", keyword: "PDF tools no watermark", benefit: "download clean documents ready for professional use" },
  { slug: "secure-document-tools", mode: "split", h1: "Secure Document Tools", metaTitle: "Secure Document Tools - Client-Side PDF Processing", description: "Handle common document tasks locally with no file upload pipeline.", keyword: "secure document tools", benefit: "minimize exposure when working with important files" },
  { slug: "client-side-pdf-tools", mode: "merge", h1: "Client-Side PDF Tools", metaTitle: "Client-Side PDF Tools - Free Local Processing", description: "PDF tools powered by browser-side JavaScript and pdf-lib, not a remote conversion server.", keyword: "client-side PDF tools", benefit: "run document processing directly on your own device" },
  { slug: "pdf-for-confidential-documents", mode: "compress", h1: "PDF Tools for Confidential Documents", metaTitle: "Private PDF Tools for Confidential Documents", description: "Process confidential PDFs locally to avoid sending source files to a third-party server.", keyword: "PDF tools confidential documents", benefit: "reduce the data-sharing surface of routine PDF work" },
  { slug: "pdf-toolkit-for-office", mode: "merge", h1: "PDF Toolkit for Office Work", metaTitle: "Free PDF Toolkit for Office & Remote Work", description: "Fast everyday PDF tools for reports, invoices, forms and scanned documents.", keyword: "PDF toolkit for office", benefit: "handle frequent office document tasks from one place" },
  { slug: "free-pdf-tools", mode: "merge", h1: "Free PDF Tools", metaTitle: "Free PDF Tools Online - Private, No Signup", description: "Merge, split, convert and clean PDFs free in your browser.", keyword: "free PDF tools", benefit: "solve common PDF tasks without subscriptions or limits" },
  { slug: "local-pdf-processing", mode: "compress", h1: "Local PDF Processing", metaTitle: "Local PDF Processing - No Server Uploads", description: "Process PDFs locally with browser memory and download the result directly.", keyword: "local PDF processing", benefit: "keep source documents inside your device boundary" },
  { slug: "browser-based-pdf-tools", mode: "split", h1: "Browser-Based PDF Tools", metaTitle: "Browser-Based PDF Tools - Fast, Free & Private", description: "Use capable PDF utilities directly in a modern desktop or mobile browser.", keyword: "browser-based PDF tools", benefit: "process documents without installing desktop software" },
  { slug: "pdf-privacy-toolkit", mode: "compress", h1: "PDF Privacy Toolkit", metaTitle: "PDF Privacy Toolkit - No Upload Document Tools", description: "Merge, extract, convert and clean PDFs with a privacy-centered local workflow.", keyword: "PDF privacy toolkit", benefit: "keep control of documents from selection through download" },
];

export function getToolPage(slug: string): ToolPage | undefined {
  return toolPages.find((page) => page.slug === slug);
}
